let g:solarized_termcolors=256

set nocompatible
syntax on
set number
set showmatch
set hlsearch

"set tabstop=4
set ai
set wrap
set si

" Yay Terminal.app + tmux + mouseterm
if has("mouse")
    set mouse=a
	set mousehide
endif

" Color Scheme
syntax enable
set background=dark
colorscheme solarized